### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by hkusulja** [snobu/php-imagick-webapps#1]
After copying files from "site" directory to a new Azure Web App, and setting variables as per screenshot.
test.php does not work.

> PHP Fatal error:  Uncaught exception 'ImagickException' with message 'unable to open module file `D:\home\.magick\IM_MOD_RL_png_.dll': No such file or directory @ warning/module.c/GetMagickModulePath/812' in D:\home\site\wwwroot\test.php:20
> Stack trace:
> #0 D:\home\site\wwwroot\test.php(20): Imagick->setimageformat('png')
> #1 {main}
>   thrown in D:\home\site\wwwroot\test.php on line 20

**Comment by hkusulja** [comment]
My issue with not uploading all dll's using Kudu interface. It works like expected.

**Comment by snobu** [comment]
I strongly recommend moving away from ImageMagick on Windows, simply due to the quality of the port (with respect to the port authors). Just run on a Linux worker in App Service, comes with ImageMagick installed -<br>

See this: https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-how-to-create-a-web-app

You can also bring in your own Docker Container -
https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-using-custom-docker-image
